runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /(.*\.(css|eot|gz|html|ico|js|map|jpg|gif|png|svg|ttf|woff|woff2))
  static_files: dist/\1
  upload: dist/(.*\.(css|eot|gz|html|ico|js|map|jpg|gif|png|svg|ttf|woff|woff2))

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  expiration: "15m"

skip_files:
  - ^(?!dist)